name: Build OldWu PE

on: [workflow_dispatch]

jobs:
  build_windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Rust & Build
        shell: pwsh
        run: |
          # 1. 自动找 Cargo.toml 在哪个文件夹
          $projDir = (Get-ChildItem -Recurse -Filter "Cargo.toml" | Select-Object -First 1).DirectoryName
          Write-Host "===> 找到项目目录: $projDir <==="
          
          # 2. 进去编译
          Set-Location $projDir
          cargo build --release
          
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: LaoWuPE_Installer
          path: '**/target/release/LetRecoveryPE.exe'
