name: Build LaoWu Installer

on: [workflow_dispatch] 

jobs:
  build_windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build Release
        # 使用 manifest-path 直接指定位置，避免进入中文名目录出错
        run: | 
          cd "PE 端"
          cargo build --release
          
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: LaoWu-PE-Installer
          path: './PE 端/target/release/LetRecoveryPE.exe'
